### PR TITLE
Fix TES

### PR DESCRIPTION
**Pull request by iamjli**
Fix for https://github.com/biocore-ntnu/pyranges/issues/182

### CODE REVIEW

**Comment by iamjli** [comment]
Also, the current implementation of `.tss` and `.tes` sometimes return positions that fall outside the transcript range by 1bp. 

For instance, for the region `chr:57212183-57214397` on the negative strand, `.tss` would give `chr:57214397-57214398`, whereas I would expect `chr:57214396-57214397`. 

I'm not sure if this was by design, but I went ahead and changed it.

**Comment by endrebak** [comment]
I think you are correct on both counts.

Since ends are non-inclusive, the last bp of 0 to 1 is 0.

Would you mind updating the CHANGELOG and pyranges/version.py? Then I can merge it as is :)

If not I’ll try to do it tomorrow. Thanks :)

**Comment by iamjli** [comment]
done

**Comment by endrebak** [comment]
Sorry for the late reply. I did not get an e-mail notification for some reason.

**Pull request merged**
