### PR TITLE
fixed empty attribute bug in read_gtf when duplicate_attr=True

### PR DESCRIPTION
**Pull request by fairliereese**
Empty attributes were accounted for in `read_gtf(duplicate_attr=False)`, but not `read_gtf(duplicate_attr=True)`. This commit fixes the bug and moves the attribute parsing code to a separate function that both `duplicate_attrs` options will call to prevent future inconsistent behavior.

### CODE REVIEW

**Comment by fairliereese** [comment]
Fixes #292

**Comment by fairliereese** [comment]
Latest commit fixes #291 by converting boolean columns into categoricals before assigning null values. 

I figured this would be the best strategy as we can't assume anything about the T/F value of a boolean variable.

**Comment by endrebak** [comment]
I will fix this tomorrow

**Comment by endrebak** [comment]
Sorry for the late reply. Thanks again.

Have updated my contact info in git so I won't be this late ever again.

**Pull request merged**
