### PR TITLE
fixes: #262; nearest without overlapping chromosomes

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
I'm not sure what a good way of solving this would be? This _kinda_ works. In that it doesn't output a working PyRanges. It however does output a valid dataframe from the PyRanges. 

Example of how this breaks pyranges

```
import pyranges

f1 = pyranges.from_dict({'Chromosome': ['chr1', 'chr2'], 'Start': [3, 8], 'End': [6, 9]})
f2 = pyranges.from_dict({'Chromosome': ['chr1'], 'Start': [1], 'End': [2]})

print("--------")

print(f1.nearest(f2).Distance)
```

Which gives a keyerror, as not each chromosome non-NA values...

### CODE REVIEW

**Comment by endrebak** [comment]
This is great. I'll look at it Monday :)

**Comment by endrebak** [comment]
Thanks. running the tests now :D

**Comment by endrebak** [comment]
It seems like the columns are promoted to float in this case:

```
>>> df
    Chromosome     Start       End Strand     Start_b       End_b Strand_b   Distance
0         chr1   6817713   6817813      +   7721048.0   7721148.0        -   903236.0
1         chr1  12415814  12415914      +  11640019.0  11640119.0        -   775696.0
2         chr1  20655161  20655261      +  26458615.0  26458715.0        +  5803355.0
3         chr1  37846510  37846610      +  34188591.0  34188691.0        -  3657820.0
4         chr1  40120478  40120578      +  43419983.0  43420083.0        -  3299406.0
..         ...       ...       ...    ...         ...         ...      ...        ...
995       chrY  31149300  31149400      -         NaN         NaN      NaN        NaN
996       chrY  28945476  28945576      -         NaN         NaN      NaN        NaN
997       chrY  54327866  54327966      -         NaN         NaN      NaN        NaN
998       chrY  29072224  29072324      -         NaN         NaN      NaN        NaN
999       chrY   1344728   1344828      -         NaN         NaN      NaN        NaN

[1000 rows x 8 columns]
>>> df.dtypes
Chromosome    category
Start            int32
End              int32
Strand        category
Start_b        float64
End_b          float64
Strand_b      category
Distance       float64
dtype: object
```

Also, this behavior is not backward-compatible, so it should be hidden behind a flag at least :)

But how about making a utility function in this case?

```
import pyranges as pr
gr = pr.random()
gr2 = pr.random()["chr1"]
r = gr.nearest(gr2)
df = r.df
chroms_missing = set(gr.chromosomes).difference(gr2.chromosomes)
n = gr.nearest(gr2)
missing_gr = pr.concat([gr[c] for c in chroms_missing])
missing_gr_double = missing_gr.join(missing_gr)

double_columns = [c for c in missing_gr_double.columns if c.endswith("_b")]

missing_gr_double.Start_b = -1
missing_gr_double.End_b = -1
missing_gr_double.Strand_b = "."

result = pr.concat([n,  missing_gr_double])

print(result)
+--------------+-----------+-----------+--------------+-----------+-----------+--------------+------------+
| Chromosome   | Start     | End       | Strand       | Start_b   | End_b     | Strand_b     | Distance   |
| (category)   | (int32)   | (int32)   | (category)   | (int32)   | (int32)   | (category)   | (int64)    |
|--------------+-----------+-----------+--------------+-----------+-----------+--------------+------------|
| chr1         | 7858971   | 7859071   | +            | 10659285  | 10659385  | -            | 2800215.0  |
| chr1         | 21834837  | 21834937  | +            | 17095296  | 17095396  | +            | 4739442.0  |
| chr1         | 29847189  | 29847289  | +            | 28424716  | 28424816  | -            | 1422374.0  |
| chr1         | 46475675  | 46475775  | +            | 46685800  | 46685900  | -            | 210026.0   |
| ...          | ...       | ...       | ...          | ...       | ...       | ...          | ...        |
| chrY         | 31391174  | 31391274  | -            | -1        | -1        | .            | nan        |
| chrY         | 48979589  | 48979689  | -            | -1        | -1        | .            | nan        |
| chrY         | 12148238  | 12148338  | -            | -1        | -1        | .            | nan        |
| chrY         | 970043    | 970143    | -            | -1        | -1        | .            | nan        |
+--------------+-----------+-----------+--------------+-----------+-----------+--------------+------------+
Stranded PyRanges object has 1,000 rows and 8 columns from 24 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
```

**Comment by Maarten-vd-Sande** [comment]
The utility function seems nice. I don't mind using it (and skipping the PR). For me it was mainly very unexpected that I would lose out on some ranges because they didn't overlap with the query. And I can imagine it's unexpected for others as well.

I will add a flag and see if I can use pandas.NA instead of having the column turn into floats. It might take some time though :smile:

**Comment by endrebak** [comment]
That is the reason for pyranges removing those entries; to avoid having to
promote columns to floats.

If you find a solution feel free to ping me and I'll help you create a PR.

**Comment by Maarten-vd-Sande** [comment]
@endrebak sorry I've been swamped with other stuff so I don't think I have time to work on this. Thanks for your help earlier with the previous solution :pray:

**Pull request closed without merging**
