### PR TITLE
Fix UnboundLocalError for 'null' variable

### PR DESCRIPTION
**Pull request by mkanai**
Hi, I encountered the following error when using `join(how="left")` with a data frame that has a dtype of [`pandas.StringDtype`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.StringDtype.html#pandas.StringDtype).
```
UnboundLocalError: local variable 'null' referenced before assignment
```

I know `pandas.StringDtype` (i.e., `string[python]` or `string[pyarrow]`) is still experimental but given the current if clauses below have the `d == "str"` condition, this PR fixes the above error. Also, I added the else clause to raise an appropriate error message.

https://github.com/biocore-ntnu/pyranges/blob/7adecd4f4f875786a92d66afb36afd5beb1e3d95/pyranges/methods/join.py#L61-L71

### CODE REVIEW

**Comment by endrebak** [comment]
I much appreciate it. Next week I am on vacation and will have ample time to look at the PR.

Endre

**Comment by endrebak** [comment]
Thanks! Cloning now to play around with the PR :D

**Comment by endrebak** [comment]
It seems like the tests are passing.

You might want to bump `version/version.py` and add a line to the `CHANGELOG`? Then you'll get full credit for the commit.

**Comment by endrebak** [comment]
Also, I'm really looking forward to be able to use nullable types and string types soon :) 

The code you are modifying there is an ugly hack.

**Comment by mkanai** [comment]
Great, thanks so much for your review! @endrebak I bumped the version to 0.0.117 and added the CHANGELOG accordingly.

**Pull request merged**
