### PR TITLE
Add option to report overlap in `join`

### PR DESCRIPTION
**Pull request by iamjli**

### CODE REVIEW

**Comment by endrebak** [comment]
Beautiful! What do you think of letting users name the overlap-column themselves? In that case, overlap should optionally take a string. But if it is a bool (True), let's call it Overlap.

Also, pleasing Codacy is not required :)

**Comment by iamjli** [comment]
I don't think that it's something users would really need since Overlap is a pretty unambiguous descriptor in most situations (at least the ones I can think of). 

Maybe there should be a general method for renaming columns like `.rename()` in pandas.

**Comment by endrebak** [comment]
I agree with you. The method can be extended later in that case and be 100% backward-compatible. Will merge when tests pass :)

**Comment by endrebak** [comment]
I will look at this later - travis-ci is acting weirdly. From experience, it is enough to wait a day and the issue will have resolved itself :)

**Pull request merged**
